name: RESEARKA Token CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Solhint
        run: npx solhint 'contracts/**/*.sol'
      - name: Run ESLint
        run: npx eslint '**/*.js'
      - name: Compile contracts
        run: npx hardhat compile
      - name: Run tests
        run: npx hardhat test
      - name: Run coverage
        run: npx hardhat coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: false
